collection/urls.py
from django.conf.urls import url

from . import views

app_name = 'collection'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all/$', views.all, name='all'),
]

vinyl_collection/urls.py
from django.conf.urls import include, url
from collection import views
from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^collection/', include('collection.urls')),
    url(r'^admin/', admin.site.urls),
]

collection/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    date_added = models.DateTimeField('date added to database')
    last_modified = models.DateTimeField('last time updated')

    # -1 is unknown
    # 0 is free
    # price in US dollars
    resale_value = models.DecimalField(max_digits=19, decimal_places=2)
    paid_value = models.DecimalField(max_digits=19, decimal_places=2)

    album_name = models.CharField(max_length=200)
    artist_name = models.CharField(max_length=200)
    skips = models.IntegerField(default=0)

    # very poor, poor, average, good, excellent, sealed
    sleeve_quality = models.CharField(max_length=20)
    vinyl_quality = models.CharField(max_length=20)

    def description_default():
        return "";

    description = models.TextField(default=description_default)


    def __str__(self):
        return "{0}: {1}".format(self.artist_name, self.album_name)

collection/views.py
from django.shortcuts import render
from django.http import Http404

from .models import Album

# Create your views here.

def index(request):
    context = {}
    return render(request, 'collection/index.html', context)

def all(request):
    all_albums = Album.objects.order_by('artist_name')
    if not all_albums:
        raise Http404("There are no albums in the database!")
    else:
        context = { 'all_albums': all_albums}
        return render(request, 'collection/all.html', context)

collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Include bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <title>{% block title %}Vinyl Collection{% endblock %}</title>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-toggleable-md navbar-inverse" style="background-color: #2F4172;">
        <button class="navbar-toggler navbar-toggler-right"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'collection:index' %}">Vinyl Collection</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <a class="nav-link" href="{% url 'collection:all' %}">Show All</a>
            </ul>
        </div>
    </nav>

    <!-- Body content -->
    <div class="container-fluid" id="content">
        <div class="row">
            <div class="col-12" style="background-color: #A8B2CC;">
                {% block page-header %}{% endblock %}
            </div>
        </div>
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap Js dependencies -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

collection/templates/collection/all.html
{% extends "base.html" %}

{% block title %}VinylC - All Records{% endblock %}

{% block content %}
<h1>Showing all records</h1>
<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Album</th>
            <th>Artist</th>
            <th>Sleeve Quality</th>
            <th>Vinyl Quality</th>
            <th>Skips</th>
        </tr>
    </thead>
    </tbody>
        {% for album in all_albums %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ album.album_name }}</td>
            <td>{{ album.artist_name }}</td>
            <td>{{ album.sleeve_quality }}</td>
            <td>{{ album.vinyl_quality }}</td>
            <td>{{ album.skips }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

collection/templates/collection/index.html
{% extends "base.html" %}

{% block title %}VinylC - HOME{% endblock %}

{% block page-header %}
<h2>Vinyl Management Home</h2>
{% endblock %}

{% block content %}
<ul>
    <li><a href="{% url 'collection:all' %}">All Records</a></li>
</ul>
{% endblock %}